export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGIN_SUCC = 'AUTH_LOGIN_SUCC';
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL';

export const AUTH_REGISTER = 'AUTH_REGISTER';
export const AUTH_REGISTER_SUCC = 'AUTH_REGISTER_SUCC';
export const AUTH_REGISTER_FAIL = 'AUTH_REGISTER_FAIL';

export const AUTH_GET_STATUS = 'AUTH_GET_STATUS';
export const AUTH_GET_STATUS_SUCC = 'AUTH_GET_STATUS_SUCC';
export const AUTH_GET_STATUS_FAIL = 'AUTH_GET_STATUS_FAIL';
