const types = {
    // AUTH ACTION TYPES
    AUTH_LOGIN: 'AUTH_LOGIN',
    AUTH_LOGIN_SUCC: 'AUTH_LOGIN_SUCC',
    AUTH_LOGIN_FAIL: 'AUTH_LOGIN_FAIL',

    AUTH_LOGOUT: 'AUTH_LOGOUT',

    AUTH_REGISTER: 'AUTH_REGISTER',
    AUTH_REGISTER_SUCC: 'AUTH_REGISTER_SUCC',
    AUTH_REGISTER_FAIL: 'AUTH_REGISTER_FAIL',

    AUTH_GET_STATUS: 'AUTH_GET_STATUS',
    AUTH_GET_STATUS_SUCC: 'AUTH_GET_STATUS_SUCC',
    AUTH_GET_STATUS_FAIL: 'AUTH_GET_STATUS_FAIL',

    // MEMO ACTION TYPES
    MEMO_POST: 'MEMO_POST',
    MEMO_POST_SUCC: 'MEMO_POST_SUCC',
    MEMO_POST_FAIL: 'MEMO_POST_FAIL',

    MEMO_GET: 'MEMO_GET',
    MEMO_GET_SUCC: 'MEMO_GET_SUCC',
    MEMO_GET_FAIL: 'MEMO_GET_FAIL',

    MEMO_PUT: 'MEMO_PUT',
    MEMO_PUT_SUCC: 'MEMO_PUT_SUCC',
    MEMO_PUT_FAIL: 'MEMO_PUT_FAIL',

    MEMO_DELETE: 'MEMO_DELETE',
    MEMO_DELETE_SUCC: 'MEMO_DELETE_SUCC',
    MEMO_DELETE_FAIL: 'MEMO_DELETE_FAIL',
}

export default types;
